#!/bin/sh

mtk_wifi_e2p_die() {
	echo "mtk wifi eeprom: " "$*"
	exit 1
}

mtk_wifi_e2p_extract() {
	local part=$1
	local offset=$2
	local count=$3
	local mtd

	. /lib/functions.sh

	mtd=$(find_mtd_part $part)
	[ -n "$mtd" ] || \
		mtk_wifi_e2p_die "no mtd device found for partition $part"

	dd if=$mtd of=/lib/firmware/$FIRMWARE bs=$count skip=$offset count=1 2>/dev/null || \
		mtk_wifi_e2p_die "failed to extract from $mtd"
}

FW="/lib/firmware/$FIRMWARE"
[ -e "$FW" ] && exit 0

[ -f "/etc/wireless/l1profile.dat" ] || exit 0

# first line "Default" is illegal in shell
cat /etc/wireless/l1profile.dat | tail -n +2 > /tmp/l1profile.sh

. /tmp/l1profile.sh

if [[ "$FIRMWARE" == "e2p" ]]; then
    EEPROM_size=`cat /proc/mtd | grep "Factory" | cut -d ' ' -f 2`
    mtk_wifi_e2p_extract "Factory" `printf "%d\n" 0x0` `printf "%d\n" 0x$EEPROM_size`
fi

rm -f /tmp/l1profile.sh

